# models.py
"""
Shared application data models.

These models define the contracts between the AI, voice, action,
scheduler, storage, and API layers.
"""

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class LeadTemperature(str, Enum):
    """Lead classification based on buying intent."""

    HOT = "hot"
    WARM = "warm"
    COLD = "cold"


class ConversationStatus(str, Enum):
    """Current state of a sales conversation."""

    CREATED = "created"
    RINGING = "ringing"
    ACTIVE = "active"
    COMPLETED = "completed"
    FAILED = "failed"


class MessageRole(str, Enum):
    """Role of a conversation message."""

    SYSTEM = "system"
    AGENT = "agent"
    CUSTOMER = "customer"


class CallbackStatus(str, Enum):
    """Status of a scheduled callback."""

    SCHEDULED = "scheduled"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    FAILED = "failed"


class ConversationMessage(BaseModel):
    """A single message exchanged during a conversation."""

    role: MessageRole
    text: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    language: Optional[str] = None


class QualificationData(BaseModel):
    """Information discovered about the customer's project."""

    budget: Optional[str] = None
    products: Optional[str] = None
    product_count: Optional[int] = None
    timeline: Optional[str] = None
    features: List[str] = Field(default_factory=list)

    # Additional context discovered naturally during conversation.
    business_description: Optional[str] = None
    decision_maker: Optional[str] = None
    objections: List[str] = Field(default_factory=list)


class Lead(BaseModel):
    """Complete lead record."""

    lead_id: str
    phone_number: str

    name: Optional[str] = None
    language: Optional[str] = None

    qualification: QualificationData = Field(
        default_factory=QualificationData
    )

    temperature: Optional[LeadTemperature] = None
    intent_score: float = 0.0

    conversation_summary: str = ""
    customer_quotes: List[str] = Field(default_factory=list)

    status: ConversationStatus = ConversationStatus.CREATED

    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class CallbackRequest(BaseModel):
    """A callback requested by the customer."""

    lead_id: str
    requested_time_text: str
    scheduled_for: Optional[datetime] = None
    status: CallbackStatus = CallbackStatus.SCHEDULED
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Conversation(BaseModel):
    """Complete conversation state."""

    conversation_id: str
    lead_id: str
    phone_number: str

    status: ConversationStatus = ConversationStatus.CREATED
    language: Optional[str] = None

    messages: List[ConversationMessage] = Field(
        default_factory=list
    )

    started_at: Optional[datetime] = None
    ended_at: Optional[datetime] = None

    whatsapp_sent_mid_call: bool = False
    whatsapp_sent_final: bool = False
    callback_requested: bool = False


class IntentResult(BaseModel):
    """Result returned by the AI intent-analysis layer."""

    score: float = Field(default=0.0, ge=0.0, le=1.0)
    temperature: LeadTemperature
    reasons: List[str] = Field(default_factory=list)
    high_intent: bool = False


class AIResponse(BaseModel):
    """Structured response generated by the AI agent."""

    text: str
    language: str
    intent: IntentResult
    qualification_updates: QualificationData = Field(
        default_factory=QualificationData
    )
    callback_request: Optional[CallbackRequest] = None